### ISSUE TITLE
Close currently-existing pull requests

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#315]
* [x] #106 give manager role access to delete yield, management and treatment records 
* [x] #217 Add sync info to machines table 
* [x] #223 Draft migration addressing issues in GH #41
* [x] #256 auto update documentation
* [x] #264 New migration to impose constraints on created_at and updated_at columns
* [x] #301 Value constraints batch 1
  * [x] Revise migration per Rob's feedback
