### ISSUE TITLE
one bug, one tweak to script for adding polygons to sites creates broken insert statement 

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#372]
Using the script from #369 on the `bety-mepp` database on ebi-forecast to specify the polygons around two sites at the energy farm.

The fields are defined by 
[energyfarm_siteB7.txt](https://github.com/PecanProject/bety/files/56051/energyfarm_siteB7.txt) and
[energyfarm_siteI5.txt](https://github.com/PecanProject/bety/files/56052/energyfarm_siteI5.txt).

If I run 

```
python26 script/buildSQLGeom.py -i ~/energyfarm_siteI5.txt -s "Energy Farm Plot I5" -d "bety-mepp" 
```

I get an error regarding credentials even though I can access the database using `psql -d bety-mepp` works.

But if I add the `-o` flag and specify the `site_id`, I can generate the .sql file and load it with the `psql` command 

```
python26 script/buildSQLGeom.py -i ~/energyfarm_siteB7.txt -s 8000000001 -d "bety-mepp" -o
psql -d bety-mepp < ~/energyfarm_siteB7_insert.sql 
```

But I get the error 

> ERROR:  geometry contains non-closed rings
> HINT:  "...0.065884214 -88.191287744 640.30035))" <-- parse error at position 158 within geometry

I get the same results if I run the query directly

### TODO

* [ ] Fix bug in insert statement
* [ ] Use global credentials for psql if available (not sure how mine are specified) 
* [x] Finished when these files are uploaded

**Comment by dlebauer** [comment]
OK. There are two bugs

1.  the vector has to start and end with the same point. But after fixing this I get an error about the espg
2. the espg needs to be 4326 (currently it was set to 3857 by default)

**Comment by dlebauer** [comment]
Additional errors:

1. If there is no elevation, then it looks for the google elevation API key in a hard-coded file path
2. Even if I use the -z flag to specify the elevation, I get the same error
3. If we are in the US, it should be using the NED instead of Google, since NED is more accurate (per #369)

**Comment by max-zilla** [comment]
https://github.com/PecanProject/bety/pull/371
I just updated this pull request with several changes:
* checks whether end point and start point are identical in source data; if not, append start point to the end of the query
* EPSG default set back to 4326
* default path for Google API key is now GOOGLE_ELEVATION_API_KEY.txt in *same directory* as the script. we can discuss making a conf file with the path, since I'm thinking about it anyway for...
* ...the credentials issue. I will look into this further and found some discussions that could help, but I may ask for some of @dlebauer's time to test it.
* fixed -z flag so it is honored when a file without z column is provided.

The USGS NED should be the default source for elevation. On line 245 we ask for NED elevation and if it returns -1000000 (i.e. outside the US) we ask Google as well. Did you encounter a situation where it appeared to be fetching Google elevation in the US?

**Comment by max-zilla** [comment]
Specifically re: credentials testing, [this](http://stackoverflow.com/questions/15692437/ident-connection-fails-via-psycopg2-but-works-via-command-line) suggests that supplying a port number and omitting user/pass entirely (possibly even omitting port number if its standard) could be sufficient. I'll start digging into this but different pgsql configs will be good to test against.

**Comment by max-zilla** [comment]
@dlebauer the text files you were using are formatted LAT,LON,Z instead of LON,LAT, Z, thus the failure of NED. It was mixing up lat/long.  
  
I didn't want to hard-code expected column headers, but I'll add a simple sanity check that at least says:
* If the column is "latitude", "lat", or "y" (case insensitive) then treat this column as latitude.
* Same for "longitude", "lon", or "x"
* Same for "altitude", "elevation" or "z" 
* if the column names aren't helpful, assume first column is X and second is Y (lon,lat) as it currently does.

If there are other likely common indicators of which is which we can check for those as well.

**Comment by dlebauer** [comment]
That's a good idea, with cases insensitivity. Thanks!

**Comment by max-zilla** [comment]
[pull request has been updated](https://github.com/PecanProject/bety/pull/371)
Script attempts to identify columns by headers before reverting to
previous assumption of (x,y,z) ordering. Valid entries:  
* **x**: longitude, long, lon, x
* **y**: latitude, lat, y
* **z**: altitude, elevation, alt, z

Added warnings when rows are missing z value if a z column was
identified.

David, with this update the script outputs the following:

energyfarm_siteB7.txt
```
UPDATE sites SET geometry = ST_Geomfromtext('POLYGON((-88.191291257 40.065353859 643.85130,-88.190411805 40.065354042 641.41716,-88.190420183 40.065870523 639.05105,-88.191287744 40.065884214 640.30035,-88.191291257 40.065353859 643.85130))', 4326) WHERE ID=8000000001
```

energyfarm_siteI5.txt (has 'elevation' header but no values)
```
UPDATE sites SET geometry = ST_Geomfromtext('POLYGON((-88.204463395 40.062806716,-88.206952545 40.062776529,-88.206951006 40.063609417,-88.205248163 40.063617384,-88.204853694 40.063849512,-88.204479037 40.063896590,-88.204463395 40.062806716))', 4326) WHERE ID=8000000001
```

**Comment by dlebauer** [comment]
Have you tested the second query? I get an error because it does not have a 'z' dimension in the update statement.

**Comment by dlebauer** [comment]
```
bety=# UPDATE sites SET geometry = ST_Geomfromtext('POLYGON((
bety'# -88.204463395 40.062806716,
bety'# -88.206952545 40.062776529,
bety'# -88.206951006 40.063609417,
bety'# -88.205248163 40.063617384,
bety'# -88.204853694 40.063849512,
bety'# -88.204479037 40.063896590,
bety'# -88.204463395 40.062806716))', 4326) WHERE ID = 189;
ERROR:  Column has Z dimension but geometry does not
```

**Comment by dlebauer** [comment]
isn't the idea that we would fill in Z from the USGS or Google API?

**Comment by max-zilla** [comment]
ahh yes, I understand now. My thinking was that it would be good to notify the user if their data had a Z column with some of the values present and others missing, i.e. indicating some error in their dataset, but no reason I shouldn't go ahead and generate the Z from the API as well. I'll keep the warning message but change it to "querying for z value."

**Comment by dlebauer** [comment]
thanks but please change 'z' for 'elevation' for a more informative message

**Comment by max-zilla** [comment]
Will update pull request momentarily. Here's the output with elevation from NED:
```
UPDATE sites SET geometry = ST_Geomfromtext('POLYGON((
-88.204463395 40.062806716 216.930328,
-88.206952545 40.062776529 216.367004,
-88.206951006 40.063609417 216.051956,
-88.205248163 40.063617384 216.367004,
-88.204853694 40.063849512 217.099136,
-88.204479037 40.063896590 217.586578,
-88.204463395 40.062806716 216.930328))', 4326) WHERE ID=8000000001
```
